### ISSUE TITLE
Suggestion : Render multiple grids on same page

### ISSUE THREAD

**Issue by Nuranto** [leantony/laravel-grid#56]

**Comment by leantony** [comment]
Absolutely, you can. Since they are all sent to laravel views the same way any other data is done. The grid overrides `toString`, so just placing the grid variable on your view should trigger that `toString` implementation. Which will render the grid itself.
Now back to your question, consider a case where you need to render `users` and `roles` as grids on one page. *This assumes you already generated the grids for yourself*. This is how you will go about it;
> UsersController, for example
```php
/**
     * Display a listing of the resource.
     *
     * @param UsersGridInterface $usersGrid
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(UsersGridInterface $usersGrid, RolesGridInterface $rolesGrid, Request $request)
    {
       // define query for roles
       $rolesQuery = Roles::query();
        // define query for users
        $usersQuery= User::query();
        // any data you need sent to the view....
        $data = ['somedata'];
        // define users grid
        $users = $usersGrid
                    ->create(['query' => $usersQuery, 'request' => $request]);
        // define roles grid
        $roles = $rolesGrid
                    ->create(['query' => $rolesQuery, 'request' => $request]);
        // send to a view
        return view('home.index', compact('users', 'roles', 'data'));
    }
```
> home.index view, for example
Now on your view, you'll just render them all on one page like this;
```php
<div class="col-md-12">
     {!! $users !!}
</div>
<hr>
<div class="col-md-12">
     {!! $roles!!}
</div>
```

**Comment by leantony** [comment]
I'll add this to the documentation, as part of the next minor release. Thanks for pointing it out.

**Comment by leantony** [comment]
Docs added in c7913c0ed14fd2ac9a3702038537a1a43d2e2a69.

**Comment by ctc1646** [comment]
Alas had a problem with multiple grids in Laravel 6 - the content of the first grid appears in the second so you just end up with two of the same. Solution: change @endsection to @overwrite on line 165 in grid.blade.php
