### ISSUE TITLE
Question (issue ?) : handleFormSubmission not triggered

### ISSUE THREAD

**Issue by Nuranto** [leantony/laravel-grid#61]
Me again :)

I cannot make pjax work for modal form submit.

I placed an alert in handleFormSubmission method, but the alert is not called.

If I execute, after the modal is loaded, this code in the console : 
```
    $('#bootstrap_modal').on('click', '#' + 'modal_form' + ' button[type="submit"]', function (e) {
        alert('ici');
      e.preventDefault();
      // process forms on the modal
      _grids.formUtils.handleFormSubmission('modal_form', $('#bootstrap_modal'));
    });
```

Then, it works...

It's very probably an issue on my side, since your demo site works... So is there something to do to make it works with pjax ? I cannot find out after comparing many times demo code and my code. And I can't see how you listen to freshly ajax-loaded modal form submit button..

I use the default create button.

Here is controller : 

```
public function editEntryForm(Request $request)
    {
       $modal = [
            'model' => class_basename(Entry::class),
            'route' => route('entry.edit.submit'),
            'action' => 'create',
            'pjaxContainer' => $request->get('ref'),
        ];
        // modal
        return view('entry_modal', compact('modal'))->render();
    }
    
    public function editEntry(Request $request)
    {
        $this->validate($request, $this->_validationRules);
        $data = $request->all();
        $entry = Entry::create($data);
        return new JsonResponse([
            'success' => true,
            'message' => __('Entry has been created.')
        ]);
    }
    
```

**Comment by leantony** [comment]
Have you read https://github.com/leantony/laravel-grid/blob/master/docs/modals.md ?

+ Oh, for modal's submit button, the listener part is [here](https://github.com/leantony/laravel-grid/blob/4e28cf73fce58c9a5bb18868b647ace599600914/src/resources/assets/js/grid.js#L460-L465). Without this, of course the modal would not be launched.

+ The modal itself is initialized on the `init` method [here](https://github.com/leantony/laravel-grid/blob/master/src/resources/assets/js/grid.js#L501). This makes the modal class available to the DOM.

+ The init method mentioned above is run both on loading the script into the DOM, and also on the [pjax.end](https://github.com/defunkt/jquery-pjax#reinitializing-pluginswidget-on-new-page-content) event of the PJAX plugin. Remember, for PJAX you'll need to re-initialize jquery plugins, otherwise you'll find that after the PJAX runs, your plugins don't work.

+ For the create button, the grid's ID, which is used as the PJAX container, is passed into the url for the modal [here](https://github.com/leantony/laravel-grid/blob/master/src/Buttons/RendersButtons.php#L111). A much easier way of enabling or disabling PJAX on a button is documented [here](https://github.com/leantony/laravel-grid/blob/master/docs/buttons.md#enabledisable-pjax-on-button-click)

+ Then, you have to pass the grid ID (`$request->get('ref')`) into the modal that you create as the `pjaxContainer` key in the data array. But this attribute is not really enforced, so null is allowed. Meaning the modal will have no PJAX container to refresh after a valid form submit as seen [here](https://github.com/leantony/laravel-grid/blob/4e28cf73fce58c9a5bb18868b647ace599600914/src/resources/assets/js/grid.js#L367-L370). So, the PJAX container will not be refreshed.

**Comment by Nuranto** [comment]
Stupid mistake of myself again. I placed grid.js before `@include('leantony::modal.container')` ... So `$('#bootstrap_modal')` returned empty and was not click-observed...

Moving container before JS solved the issue..

But, your answer helped me to understand and solve my issue, it is very complete and should be in the doc ! 
Thank you.

**Comment by leantony** [comment]
Will add to the docs as requested. Thanks.
