### ISSUE TITLE
Leantony\Grid\Grid::getPageSize() 

### ISSUE THREAD

**Issue by AndreaRunner** [leantony/laravel-grid#9]
I've created model, table (populate table), grid, route and made this controller:

 public function index(SalsGridInterface $salsGrid, Request $request) {

        //return $salsGrid->create(['query' => Sal::with('role'), 'request' => $request])
        return $salsGrid
                        ->create(['query' => Sal::all(), 'request' => $request])
                        ->renderOn('render_grid', [
                'generation_command' => 'php artisan make:grid --model="App\User"',
                'grid_code' => "https://gist.github.com/leantony/52793560fe98cab2440b829c3b3f8d9f.js",
            ]);
    }

but i've this problem:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Return value of Leantony\Grid\Grid::getPageSize() must be of the type integer, null returned

 protected function getPageSize(): int
    {
        return config('grids.pagination_limit');
    }

Where is my mistake ?
Thanks in advance

**Comment by leantony** [comment]
Try publishing the config by running;
`php artisan vendor:publish --provider="Leantony\Grid\Providers\ServiceProvider" --tag=config`

**Comment by leantony** [comment]
Your code has issues also
+ You need to supply an instance of the query builder to the grid. Not a collection `Sal::all()` returns a collection. Use `Sal::query()`, or any other variant that returns a builder. Do not actually run the eloquent query, as the grid will do this for you automatically
+ `renderOn` calls the laravel helper function `view('name', compact('data'))` behind the scenes. So you can pass any data you want. So you don't really need ` 'generation_command' => 'php artisan make:grid --model="App\User"',`, and `grid_code`. I use those on the example app to ensure that the gist and the appropriate commands are displayed on the UI, since I needed them.
```php
public function index(SalsGridInterface $salsGrid, Request $request) {
    return $salsGrid
                    ->create(['query' => Sal::query(), 'request' => $request])
                    ->renderOn('render_grid'); // this is the same as view('viwename', compact('data'))
}
```
